### ISSUE TITLE
Ioncube 10.2 PHP 7.2 not working

### ISSUE THREAD

**Issue by Setiawan007** [tahaghafuri/ioncube_decoder#1]
Hello sir, I try this repo to decode ioncube 10.2 PHP 7.2 but it's not working. Any Solution? Thanks

**Comment by tahaghafuri** [comment]
Hi,Require Patch Files And Change And Upgrade Codes To PHP 7.4:
[phpexpress-php-5.3.dll](https://github.com/tahaghafuri/ioncube_decoder/blob/main/ioncube/phpexpress-php-5.3.dll)
[ZendLoader.dll](https://github.com/tahaghafuri/ioncube_decoder/blob/main/ioncube/ZendLoader.dll)
[Zend](https://github.com/tahaghafuri/ioncube_decoder/tree/main/ioncube/Zend)
After Patching Decodes Work,
Me Can't Decode The Files And Upgrade The Codes.

**Comment by MoustafaKamel1995** [comment]
hi 
Please, the script is not working
